
# I'm not doing anything fancy here.
# Compile and run. ~~No optimizations.~~ (It's already fast as-is)

compile:
	gcc -Wall *.c *.h -o test
run:
	gcc -Wall *.c *.h -o test
	./test

# Testing optimizations.

optimized:
	gcc -Wall -O2 *.c *.h -o engine